CREATE TABLE EMPLOYEE(
    UNIQUE_CODE     CHAR(9)     PRIMARY KEY,
    FNAME       VARCHAR(15)     NOT NULL,
    LNAME       VARCHAR(15)     NOT NULL,
    GENDER      CHAR,
    ADDRESS     VARCHAR(30),
    START_DATE      DATE,
    SPECIALTY_NAME  VARCHAR(20)     NOT NULL,
    DEGREE_YEAR     SMALLINT    NOT NULL,
    DEPT_UC     CHAR(3)     NOT NULL
);
CREATE TABLE NURSE(
    UNIQUE_CODE     CHAR(9)       PRIMARY KEY,
    CONSTRAINT nurse_emp_fk
    FOREIGN KEY(UNIQUE_CODE) REFERENCES EMPLOYEE(UNIQUE_CODE)
    ON DELETE CASCADE
);
CREATE TABLE DOCTOR(
    UNIQUE_CODE      CHAR(9)     PRIMARY KEY,
    CONSTRAINT doctor_emp_fk
    FOREIGN KEY(UNIQUE_CODE) REFERENCES EMPLOYEE(UNIQUE_CODE)
    ON DELETE CASCADE
);
CREATE TABLE DEAN(
    UNIQUE_CODE     CHAR(9)        PRIMARY KEY,
    CONSTRAINT dean_doctor_fk
    FOREIGN KEY(UNIQUE_CODE) REFERENCES  EMPLOYEE(UNIQUE_CODE)
    ON DELETE CASCADE
);
CREATE TABLE DEPARTMENT(
    UNIQUE_CODE         CHAR(3)     PRIMARY KEY,
    TITLE       VARCHAR(20)     NOT NULL,
    DEAN_UC     CHAR(9)      NOT NULL,
    CONSTRAINT dept_dean_fk
    FOREIGN KEY(DEAN_UC) REFERENCES DEAN(UNIQUE_CODE)
    ON DELETE SET NULL DEFERRABLE
);
CREATE TABLE PHONE_NUMBER(
    PHONE_NUM      NUMBER(10)       UNIQUE,
    EMP_UC          CHAR(9),
    CONSTRAINT phone_pk
    PRIMARY KEY(PHONE_NUM, EMP_UC),
    CONSTRAINT phone_emp_fk
    FOREIGN KEY(EMP_UC) REFERENCES EMPLOYEE(UNIQUE_CODE)
    ON DELETE CASCADE
);
ALTER TABLE EMPLOYEE
ADD CONSTRAINT emp_dept_fk
FOREIGN KEY(DEPT_UC) REFERENCES DEPARTMENT(UNIQUE_CODE)
ON DELETE SET NULL;
CREATE TABLE EXAMINATION(
    EXAM_ID     CHAR(10)    PRIMARY KEY,
    EXAMINATE_DATE      DATE,
    DIAGNOSIS       VARCHAR(50)     NOT NULL,
    RESULT          VARCHAR(20)     NOT NULL,
    NEXT_EX         DATE,
    FEE             DECIMAL(10,2),
    RECORD_ID    CHAR(10)     NOT NULL,
    CONSTRAINT exam_rec_fk
    FOREIGN KEY(RECORD_ID) REFERENCES OUTPATIENT_RECORD(RECORD_ID)
    ON DELETE SET NULL
);

CREATE TABLE INPATIENT(
    ID      CHAR(7)     PRIMARY KEY,
    IPCODE      CHAR(9)     NOT NULL,
    FNAME       VARCHAR(15)     NOT NULL,
    LNAME       VARCHAR(15)     NOT NULL,
    GENDER      CHAR,
    ADDRESS     VARCHAR(30),
    DOB         DATE,
    PHONE_NO    NUMBER(10)      NOT NULL    UNIQUE,
    NURSE_UC    CHAR(9)     NOT NULL,
    CONSTRAINT ip_nurse_fk
    FOREIGN KEY(NURSE_UC) REFERENCES NURSE(UNIQUE_CODE)
    ON DELETE SET NULL
);
CREATE TABLE OUTPATIENT(
    ID      CHAR(7)      PRIMARY KEY,
    OPCODE      VARCHAR(9)     NOT NULL,
    FNAME     VARCHAR(15)       NOT NULL,
    LNAME     VARCHAR(15)       NOT NULL,
    GENDER      CHAR,
    ADDRESS      VARCHAR(30),
    DOB         DATE,
    PHONE_NO    NUMBER(10)      NOT NULL UNIQUE
);
CREATE TABLE EXAMINE(
    EXAM_ID     CHAR(10)    NOT NULL,
    DOCTOR_ID   CHAR(9)     NOT NULL,
    OP_ID       CHAR(7)     NOT NULL,
    CONSTRAINT examine_pk
    PRIMARY KEY(EXAM_ID, DOCTOR_ID),
    CONSTRAINT examine_exam_fk 
    FOREIGN KEY(EXAM_ID) REFERENCES EXAMINATION(EXAM_ID)
    ON DELETE CASCADE,
    CONSTRAINT examine_doctor_fk
    FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(UNIQUE_CODE)
    ON DELETE CASCADE,
    CONSTRAINT examine_op_fk 
    FOREIGN KEY(OP_ID) REFERENCES OUTPATIENT(ID)
    ON DELETE CASCADE
);
CREATE TABLE INPATIENT_RECORD(
    RECORD_ID    CHAR(10)   PRIMARY KEY,
    ADMISSION_DATE      DATE,
    DIAGNOSIS           VARCHAR(50),
    DISCHARGE_DATE      DATE,
    SICK_ROOM       NUMBER(3),
    TOTAL_FEE             DECIMAL(10,2),
    IP_ID           CHAR(7)      NOT NULL,
    CONSTRAINT record_ip_fk
    FOREIGN KEY(IP_ID) REFERENCES INPATIENT(ID)
    ON DELETE SET NULL
);
CREATE TABLE OUTPATIENT_RECORD(
    RECORD_ID   CHAR(10)    PRIMARY KEY,
    TOTAL_FEE   DECIMAL(10,2),
    OP_ID       CHAR(7)        NOT NULL,
    CONSTRAINT record_op_fk
    FOREIGN KEY(OP_ID) REFERENCES OUTPATIENT(ID)
    ON DELETE SET NULL
);
CREATE TABLE MEDICATION(
    UNIQUE_CODE     CHAR(6)     PRIMARY KEY,
    NAME        VARCHAR(20)     NOT NULL,
    CURRENT_PRICE       DECIMAL(10,2),
    TOTAL_QUANTITY  INT
);
CREATE TABLE EXAM_USE_MED(
    EXAM_ID      CHAR(10),
    MED_ID      CHAR(6),
    DOSAGE      INT     NOT NULL,
    CONSTRAINT exam_use_med_pk
    PRIMARY KEY(EXAM_ID, MED_ID),
    CONSTRAINT use_exam_fk
    FOREIGN KEY(EXAM_ID) REFERENCES EXAMINATION(EXAM_ID)
    ON DELETE CASCADE,
    CONSTRAINT use_exam_med_fk
    FOREIGN KEY(MED_ID) REFERENCES MEDICATION(UNIQUE_CODE)
    ON DELETE CASCADE
);
CREATE TABLE MED_EFFECT(
    MED_UC      CHAR(6),
    MED_EFFECT     VARCHAR(30),
    CONSTRAINT med_effect_pk
    PRIMARY KEY(MED_UC, MED_EFFECT),
    CONSTRAINT effect_med_fk
    FOREIGN KEY(MED_UC) REFERENCES MEDICATION(UNIQUE_CODE)
);
CREATE TABLE TREATMENT(
    TREATMENT_ID        CHAR(10)     PRIMARY KEY,
    RESULT      VARCHAR(30)       NOT NULL,
    START_DATE      DATE,
    END_DATE        DATE,
    RECORD_ID       CHAR(10)        NOT NULL,
    CONSTRAINT treat_rec_fk
    FOREIGN KEY(RECORD_ID) REFERENCES INPATIENT_RECORD(RECORD_ID)
    ON DELETE SET NULL
);
CREATE TABLE TREAT(
    TREATMENT_ID       CHAR(10)        NOT NULL,
    DOCTOR_ID       CHAR(9)         NOT NULL,
    IP_ID       CHAR(7)     NOT NULL,
    CONSTRAINT treat_pk 
    PRIMARY KEY(TREATMENT_ID, DOCTOR_ID),
    CONSTRAINT treat_treatment_fk
    FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID)
    ON DELETE CASCADE,
    CONSTRAINT treat_doctor
    FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(UNIQUE_CODE)
    ON DELETE CASCADE,
    CONSTRAINT treat_ip_fk
    FOREIGN KEY(IP_ID) REFERENCES INPATIENT(ID)
    ON DELETE CASCADE
);
CREATE TABLE TREAT_USE_MED(
    TREATMENT_ID        CHAR(10), 
    MED_ID      CHAR(6),
    DOSAGE      INT    NOT NULL,
    CONSTRAINT treat_use_med 
    PRIMARY KEY(TREATMENT_ID, MED_ID),
    CONSTRAINT use_treatment_fk
    FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID)
    ON DELETE CASCADE,
    CONSTRAINT use_treat_med_fk
    FOREIGN KEY(MED_ID) REFERENCES MEDICATION(UNIQUE_CODE)
    ON DELETE CASCADE
);
CREATE TABLE PROVIDER(
    UNIQUE_NUMBER   NUMBER(5)   PRIMARY KEY,
    NAME        VARCHAR(15)     NOT NULL,
    ADDRESS     VARCHAR(30),
    PHONE       NUMBER(10)      NOT NULL     UNIQUE
);
ALTER TABLE DEPARTMENT
MODIFY(TITLE       VARCHAR(20)   UNIQUE);
ALTER TABLE MEDICATION
MODIFY(NAME          VARCHAR(20)     UNIQUE);
CREATE TABLE MEDICINE(
    MED_ID	CHAR(10)	PRIMARY KEY,
	EXPIRATION_DATE     DATE	NOT NULL,
	EXPIRED	    CHAR,
    BOX_QUANTITY 	INT,
    MEDICATION_UC	CHAR(6)		NOT NULL,	
    CONSTRAINT medicine_med_fk
    FOREIGN KEY(MEDICATION_UC)   REFERENCES MEDICATION(UNIQUE_CODE)
);
CREATE TABLE PROVIDE(
    MED_ID	CHAR(10) 	NOT NULL,
	PROV_NO  	NUMBER(5)   	NOT NULL,
	IMPORTTED_PRICE 		DECIMAL(10,2),
	IMPORTED_DATE		DATE,
	QUANTITY		INT, 
	CONSTRAINT provide_pk
    PRIMARY KEY(MED_ID, PROV_NO),
    CONSTRAINT prov_med_fk
    FOREIGN KEY(MED_ID)   REFERENCES MEDICINE(MED_ID)
    ON DELETE CASCADE, 
    CONSTRAINT prov_provider_fk
    FOREIGN KEY(PROV_NO)   REFERENCES PROVIDER(UNIQUE_NUMBER)
    ON DELETE CASCADE
);